### ISSUE TITLE
Lab 1 report feedback

### ISSUE THREAD

**Issue by daniel-n-ryu** [skyeyestang99/cse15l-lab-reports#1]
-------
##Rubric:
```
Here is your feedback for Lab Report 1:

- [ ] All relevant URLs written as markdown links
  - Include VSCode link to specify which version and what specific software to install
- [ ] All relevant code examples written with backticks (```)
  - Professional convention for indicating code
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Needs keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
- Well done! Just add keystrokes, add a vscode link, and apply backticks to your commands and your website will be good to go!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page
```

---------

**Comment by skyeyestang99** [comment]
what are keyst

> ##Rubric:
> 
> ```
> Here is your feedback for Lab Report 1:
> 
> - [ ] All relevant URLs written as markdown links
>   - Include VSCode link to specify which version and what specific software to install
> - [ ] All relevant code examples written with backticks (```)
>   - Professional convention for indicating code
> - [x] All screenshots correspond to the described steps
> - [x] All titles of sections are formatted as headers or similar
> - [x] Lab report is on its own page, not the index page
> - [ ] Last example counts keystrokes and shows how to run remotely saving time
>   - Needs keystrokes
> - [x] Text is formatted in a way that was easy for grader to read
> 
> Additional comments from your grader:
> - Well done! Just add keystrokes, add a vscode link, and apply backticks to your commands and your website will be good to go!
> 
> --------
> 
> If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:
> 
> - Link to this issue
> - Link to your published lab report page
> ``` what are keystrokes

**Comment by daniel-n-ryu** [comment]
To clarify: Keystrokes are the number of times you have to press a key on a keyboard. You can measure time saved using keystrokes. For example. if I put multiple commands together on the same line, how many keystrokes does that save me compared to inputting one command at a time?

**Comment by skyeyestang99** [comment]
Got it! Just updated the changes on my webpage. Thank you so much for the
clarification.

Yizhou

**Comment by skyeyestang99** [comment]
Hi Daniel!

I submitted my lab report 1 regrade this Monday. When will I get my
feedback back? Did my new updates qualify the requirements? Thank you!

Best,

Yizhou Tang

**Comment by daniel-n-ryu** [comment]
Well done, sorry for not responding
